# Generated by Django 4.2.30 on 2026-06-15 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_pipeline', '0002_rubricscore_is_evaluated_via_fallback'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='application',
            name='unique_job_candidate',
        ),
    ]
