/**
 * FallbackAlert — icon + tooltip surfaced on rows where
 * RubricScore.is_evaluated_via_fallback is true.
 *
 * Signals to the reviewer that the primary LLM provider was unavailable
 * and the score was generated by the secondary fallback provider.
 */

export default function FallbackAlert() {
  return (
    <span
      className="fallback-alert"
      title="Evaluated by backup LLM provider — manual review recommended"
      aria-label="Evaluated by backup model"
      role="img"
    >
      ⚠
    </span>
  );
}
